# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b2ab925118643bc30dc2e84eb7fac81355c441fe98e1827e33acef0be7eacc1cfa49424a37a283c93b47dd92c4ab17f519bcda665ae72bb78f3eb266e1f7be

test:
  secret_key_base: a2654e27389d0918e1d976ae49a24c38d4c30243ea9e659e932bdca0951c394aad5298d0ae36019ca3084d03c6b4c69f6dd895fd3e739f8d91ece649627f59ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
